language: c

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: BUILD_TYPE=docker
           DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
           SUFFIX=x86_64
    - sudo: required
      services:
        - docker
      env: BUILD_TYPE=docker
           DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32
           SUFFIX=i686
    - os: linux
      env: BUILD_TYPE=make
    - os: linux
      env: BUILD_TYPE=cmake
    - os: osx
      osx_image: xcode8.3
      env: BUILD_TYPE=cmake
           MAYBE_ARCH=-DCMAKE_OSX_ARCHITECTURES="i386;x86_64"
    - os: osx
      osx_image: xcode7.3
      env: BUILD_TYPE=cmake
           MAYBE_ARCH=-DCMAKE_OSX_ARCHITECTURES="i386;x86_64"
    - os: osx
      osx_image: xcode6.4
      env: BUILD_TYPE=cmake
           MAYBE_ARCH=-DCMAKE_OSX_ARCHITECTURES="i386;x86_64"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rvm get stable || true; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update || true; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake || brew upgrade cmake || true; fi

install:
  - if [[ "$BUILD_TYPE" == "docker" ]]; then docker pull $DOCKER_IMAGE; fi

script:
  - if [[ "$BUILD_TYPE" == "docker" ]]; then docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-docker.sh $SUFFIX; fi
  - if [[ "$BUILD_TYPE" == "make" ]]; then autoreconf -fi && ./configure && make -j 4 && make check -j 4; fi
  - if [[ "$BUILD_TYPE" == "make" ]]; then make dist && make dist-zip && mkdir dist && mv parasail-*.tar.gz dist && mv parasail-*.zip dist; fi
  - if [[ "$BUILD_TYPE" == "cmake" ]]; then cmake . $MAYBE_ARCH; fi
  - if [[ "$BUILD_TYPE" == "cmake" ]]; then cmake --build . --config Release; fi
  - if [[ "$BUILD_TYPE" == "cmake" ]]; then cmake --build . --config Release --target package; fi

deploy:
  provider: releases
  api_key:
    secure: jcuKmFSZD93XYyCGxl6wa1DuJBO87vDUehlxyLVldLoYS4xfXkItQIAZUjVnBOw89liV/RhMz+ceMA/qONgWAt2bpOqFUv16m7HtsGLFYZzIXdq3icSW8pOZToHLwUViLW4eDyb9I/pjUagVcn76wrpE9dlAAJwDpxCDwZLot0XIaG0AFRlj4YCqJzElHZOdGi05Zt0hE7CI7YsYeZq7O6m5lr0DvL7xo0KEsw9OiynYqRFXBZfwhrP2M4y+KIJp1V+LWm43/EL/l2HTiZHuu04RZRMWm1vB3Tuej4qF2iCVPgkw6Yp6EZcSM/P6sEnpMvtsoZkQVdJXBJRQhwOFjuOKr5gE37cixXuv2LjGIPIHhBRKgh/d4nvsbKFDdOPK8h2UW4utZ+VmnUqzH6SG//ZSVEzZLhLiPJNV96LLWNctnUHiNPy1ag6C9p6tsSSLV96xxlrpLm8EfJrJzNBGC+d83QPiKBSw8z1KKSFG4RlVUpG1MtCtY47bZaklY0zyVNp9Jpw0arQrbmPD7ykI/Hhvoa4l9kLlgN4ZYVf34e9h/XqvSaQ0qseY1az9NdbU1CfXzsHyOsylqzcLZNFZUtjaBHWxmwT9E+lzDOGPyCNGk/DbYiiQmz9jExqENIo0Ap69/v7FbGiLJiMm1jcEJUHmqudRn05FLP8lBdVQkq4=
  file: dist/*
  skip_cleanup: true
  file_glob: true
  draft: true
  tag_name: $TRAVIS_TAG
  on:
    repo: jeffdaily/parasail
    tags: true
    condition: $TRAVIS_OS_NAME = "osx" || $BUILD_TYPE = "docker" || $BUILD_TYPE = "make"

